# Generated by Django 5.0 on 2025-12-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cookprofile_address_alter_cookprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookprofile',
            name='is_available_now',
            field=models.BooleanField(default=False),
        ),
    ]
