# Generated by Django 5.0 on 2026-01-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cookprofile_is_available_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookprofile',
            name='certificate_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for certificate rejection if applicable'),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='certificate_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='fssai_certificate',
            field=models.ImageField(blank=True, help_text='Upload FSSAI certificate sample', null=True, upload_to='fssai_certificates/'),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='fssai_certificate_number',
            field=models.CharField(blank=True, help_text='FSSAI registration number', max_length=100),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='fssai_certificate_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
    ]
