# Generated by Django 5.0 on 2026-01-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cookprofile_certificate_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookprofile',
            name='fssai_expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date entered by cook', null=True),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='fssai_number',
            field=models.CharField(blank=True, help_text='FSSAI number entered by cook', max_length=20),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='fssai_ocr_confidence',
            field=models.FloatField(blank=True, help_text='OCR confidence score', null=True),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='fssai_ocr_expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date extracted by OCR', null=True),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='fssai_ocr_number',
            field=models.CharField(blank=True, help_text='FSSAI number extracted by OCR', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='fssai_risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', max_length=10),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='fssai_verification_notes',
            field=models.TextField(blank=True, help_text='AI/Manual verification notes', null=True),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='fssai_verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
