# Generated by Django 5.0 on 2026-02-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cookprofile_fssai_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookprofile',
            name='fssai_ocr_confidence',
        ),
        migrations.RemoveField(
            model_name='cookprofile',
            name='fssai_ocr_expiry_date',
        ),
        migrations.RemoveField(
            model_name='cookprofile',
            name='fssai_ocr_number',
        ),
        migrations.RemoveField(
            model_name='cookprofile',
            name='fssai_risk_level',
        ),
        migrations.RemoveField(
            model_name='cookprofile',
            name='fssai_verification_notes',
        ),
        migrations.RemoveField(
            model_name='cookprofile',
            name='fssai_verification_status',
        ),
        migrations.RemoveField(
            model_name='cookprofile',
            name='verified_at',
        ),
    ]
