# Generated by Django 5.0 on 2026-01-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerreview',
            old_name='rating',
            new_name='overall_rating',
        ),
        migrations.AddField(
            model_name='buyerreview',
            name='food_photo',
            field=models.ImageField(blank=True, null=True, upload_to='review_food_photos/'),
        ),
        migrations.AddField(
            model_name='buyerreview',
            name='freshness_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor - Stale/Old'), (2, 'Fair - Slightly stale'), (3, 'Good - Fresh'), (4, 'Very Good - Very Fresh'), (5, 'Excellent - Extremely Fresh')], null=True),
        ),
        migrations.AddField(
            model_name='buyerreview',
            name='hygiene_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor - Very unsanitary'), (2, 'Fair - Some hygiene concerns'), (3, 'Good - Generally hygienic'), (4, 'Very Good - Very clean'), (5, 'Excellent - Impeccably clean')], null=True),
        ),
        migrations.AddField(
            model_name='buyerreview',
            name='packaging_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor - Damaged/leaking'), (2, 'Fair - Some issues'), (3, 'Good - Adequate packaging'), (4, 'Very Good - Well packaged'), (5, 'Excellent - Premium packaging')], null=True),
        ),
        migrations.AddField(
            model_name='buyerreview',
            name='taste_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor - Inedible'), (2, 'Fair - Barely edible'), (3, 'Good - Acceptable taste'), (4, 'Very Good - Delicious'), (5, 'Excellent - Exceptional taste')], null=True),
        ),
        migrations.AlterField(
            model_name='buyerreview',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
