# Generated by Django 5.0 on 2026-03-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_rename_rating_buyerreview_overall_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerreview',
            name='sentiment_score',
        ),
    ]
