# Generated by Django 5.0 on 2026-01-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='nutrition_info',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_category',
            field=models.CharField(choices=[('regular', 'Regular Meal'), ('healthy', 'Healthy/Salad'), ('special', 'Special Dish')], default='regular', help_text='Categorize as healthy/salad for health-focused meals', max_length=20),
        ),
        migrations.CreateModel(
            name='HealthyDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_tags', models.JSONField(blank=True, default=list, help_text='Tags like ["vegan", "low-calorie", "gluten-free"]')),
                ('featured', models.BooleanField(default=False, help_text='Display in featured healthy diets section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='healthy_diet', to='cooks.meal')),
            ],
            options={
                'verbose_name_plural': 'Healthy Diets',
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
