# Generated by Django 5.0 on 2026-03-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0002_remove_meal_nutrition_info_meal_meal_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookreview',
            name='sentiment_score',
        ),
    ]
