# Generated by Django 5.0 on 2026-03-15 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0003_remove_cookreview_sentiment_score'),
        ('live_streaming', '0002_livestream_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupslot',
            name='cooking_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickupslot',
            name='cutoff_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickupslot',
            name='live_stream',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='live_streaming.livestream'),
        ),
    ]
