# Generated by Django 5.0 on 2026-02-11 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_rename_rating_buyerreview_overall_rating_and_more'),
        ('live_streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order this stream is for (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_streams', to='buyers.buyerorder'),
        ),
    ]
